In [1]:
import pandas as pd
from pathlib import Path

In [2]:
data_path = Path("../data/structured")

print(data_path)

../data/structured

In [3]:
employees = pd.read_csv(data_path / "employees.csv")
attendance = pd.read_csv(data_path / "attendance.csv")
leave = pd.read_csv(data_path / "leave.csv")
holidays = pd.read_csv(data_path / "holidays.csv")

In [4]:
print("Employees:", employees.shape)
print("Attendance:", attendance.shape)
print("Leave:", leave.shape)
print("Holidays:", holidays.shape)

Employees: (250, 10)
Attendance: (41750, 6)
Leave: (1550, 7)
Holidays: (9, 2)

In [5]:
print("EMPLOYEES")
display(employees.head())

print("\nATTENDANCE")
display(attendance.head())

print("\nLEAVE")
display(leave.head())

print("\nHOLIDAYS")
display(holidays.head())

EMPLOYEES

,employee_id,name,department,role,employment_type,vacation_days,weekly_hours,office_location,manager_id,email
0,E0001,Anna Müller,Data & AI,Data Analyst,Full-time,30,40,Stuttgart,NaN,anna.mueller@nexatech.example
1,E0002,Lukas Müller,Sales,Sales Manager,Full-time,30,40,Aalen,NaN,lukas.mueller@nexatech.example
2,E0003,Sophie Müller,Data & AI,Data Scientist,Full-time,30,40,Stuttgart,NaN,sophie.mueller@nexatech.example
3,E0004,Daniel Müller,Engineering,Software Engineer,Full-time,30,40,Stuttgart,NaN,daniel.mueller@nexatech.example
4,E0005,Laura Müller,Engineering,DevOps Engineer,Full-time,30,40,Aalen,NaN,laura.mueller@nexatech.example

ATTENDANCE

  employee_id        date check_in check_out location   status
0       E0001  2026-01-02    09:07     16:54     home  present
1       E0001  2026-01-05    07:58     16:34     home  present
2       E0001  2026-01-06    07:53     16:43   office  present
3       E0001  2026-01-07    08:22     16:57   office  present
4       E0001  2026-01-08      NaN       NaN      NaN    leave

LEAVE

  leave_id employee_id  start_date    end_date      type    status  days
0   L00001       E0001  2026-01-08  2026-01-08  vacation  approved     1
1   L00002       E0001  2026-01-21  2026-01-21      sick  approved     1
2   L00003       E0001  2026-02-12  2026-02-12  vacation  approved     1
3   L00004       E0001  2026-02-17  2026-02-17      sick  approved     1
4   L00005       E0001  2026-03-05  2026-03-05  vacation  approved     1

HOLIDAYS

         date            name
0  2026-01-01  New Year's Day
1  2026-04-03     Good Friday
2  2026-04-06   Easter Monday
3  2026-05-01      Labour Day
4  2026-05-14   Ascension Day

In [6]:
attendance["date"] = pd.to_datetime(attendance["date"])

leave["start_date"] = pd.to_datetime(leave["start_date"])
leave["end_date"] = pd.to_datetime(leave["end_date"])

holidays["date"] = pd.to_datetime(holidays["date"])

In [7]:
print(attendance.dtypes)

employee_id               str
date           datetime64[us]
check_in                  str
check_out                 str
location                  str
status                    str
dtype: object

In [9]:
employee_id = "E0001"

employee_attendance = attendance[
    attendance["employee_id"] == employee_id
]

display(employee_attendance.head(20))

   employee_id       date check_in check_out location   status
0        E0001 2026-01-02    09:07     16:54     home  present
1        E0001 2026-01-05    07:58     16:34     home  present
2        E0001 2026-01-06    07:53     16:43   office  present
3        E0001 2026-01-07    08:22     16:57   office  present
4        E0001 2026-01-08      NaN       NaN      NaN    leave
5        E0001 2026-01-09    09:08     17:58     home  present
6        E0001 2026-01-12    08:14     16:52   office  present
7        E0001 2026-01-13    08:25     16:52     home  present
8        E0001 2026-01-14    07:56     15:47     home  present
9        E0001 2026-01-15    08:01     16:23     home  present
10       E0001 2026-01-16    09:21     17:07   office  present
11       E0001 2026-01-19    08:58     16:57     home  present
12       E0001 2026-01-20    08:56     17:11   office  present
13       E0001 2026-01-21      NaN       NaN      NaN     sick
14       E0001 2026-01-22    09:23     17:06     home  present
15       E0001 2026-01-23    07:48     16:07     home  present
16       E0001 2026-01-26    08:03     16:34   office  present
17       E0001 2026-01-27    07:56     16:03     home  present
18       E0001 2026-01-28    08:24     16:14   office  present
19       E0001 2026-01-29    07:51     16:05   office  present

In [10]:
start_date = "2026-08-01"
end_date = "2026-08-31"

august_attendance = attendance[
    (attendance["employee_id"] == employee_id) &
    (attendance["date"] >= start_date) &
    (attendance["date"] <= end_date)
]

display(august_attendance)

    employee_id       date check_in check_out       location            status
146       E0001 2026-08-03    08:53     16:37         office           present
147       E0001 2026-08-04    08:07     15:51         office           present
148       E0001 2026-08-05    09:20     17:37         office           present
149       E0001 2026-08-06    07:58     16:20         office           present
150       E0001 2026-08-07    08:48     16:45  business_trip           present
151       E0001 2026-08-10    07:59     16:37         office           present
152       E0001 2026-08-11      NaN       NaN           home           missing
153       E0001 2026-08-12    09:11     17:13         office           present
154       E0001 2026-08-13    08:39     16:30           home           present
155       E0001 2026-08-14    08:46       NaN         office  missing_checkout
156       E0001 2026-08-17    08:19     16:37         office           present
157       E0001 2026-08-18    08:31     16:18         office           present
158       E0001 2026-08-19    09:12     17:31         office           present
159       E0001 2026-08-20    08:32     16:40           home           present
160       E0001 2026-08-21    09:02     17:52         office           present
161       E0001 2026-08-24    08:12     16:02           home           present
162       E0001 2026-08-25    08:57     17:47         office           present
163       E0001 2026-08-26    08:06     16:52         office           present
164       E0001 2026-08-27    09:37     18:14           home           present
165       E0001 2026-08-28    08:43     17:22         office           present
166       E0001 2026-08-31      NaN       NaN         office           missing

In [11]:
office_days = (
    august_attendance["location"] == "office"
).sum()

print(f"Office days in August: {office_days}")

Office days in August: 15

In [12]:
home_days = (
    august_attendance["location"] == "home"
).sum()

print(f"Home-office days in August: {home_days}")

Home-office days in August: 5

In [13]:
missing_records = august_attendance[
    august_attendance["status"].isin(
        ["missing", "missing_checkout"]
    )
]

display(missing_records)

    employee_id       date check_in check_out location            status
152       E0001 2026-08-11      NaN       NaN     home           missing
155       E0001 2026-08-14    08:46       NaN   office  missing_checkout
166       E0001 2026-08-31      NaN       NaN   office           missing

In [14]:
print(
    f"Missing attendance records: "
    f"{len(missing_records)}"
)

Missing attendance records: 3

In [ ]:
def get_attendance(
    employee_id,
    start_date,
    end_date
):
    """
    Return attendance records for an employee
    within a specified date range.
    """

    start_date = pd.to_datetime(start_date)
    end_date = pd.to_datetime(end_date)

    result = attendance[
        (attendance["employee_id"] == employee_id) &
        (attendance["date"] >= start_date) &
        (attendance["date"] <= end_date)
    ].copy()

    return result

In [16]:
result = get_attendance(
    employee_id="E0001",
    start_date="2026-08-01",
    end_date="2026-08-31"
)

display(result)

    employee_id       date check_in check_out       location            status
146       E0001 2026-08-03    08:53     16:37         office           present
147       E0001 2026-08-04    08:07     15:51         office           present
148       E0001 2026-08-05    09:20     17:37         office           present
149       E0001 2026-08-06    07:58     16:20         office           present
150       E0001 2026-08-07    08:48     16:45  business_trip           present
151       E0001 2026-08-10    07:59     16:37         office           present
152       E0001 2026-08-11      NaN       NaN           home           missing
153       E0001 2026-08-12    09:11     17:13         office           present
154       E0001 2026-08-13    08:39     16:30           home           present
155       E0001 2026-08-14    08:46       NaN         office  missing_checkout
156       E0001 2026-08-17    08:19     16:37         office           present
157       E0001 2026-08-18    08:31     16:18         office           present
158       E0001 2026-08-19    09:12     17:31         office           present
159       E0001 2026-08-20    08:32     16:40           home           present
160       E0001 2026-08-21    09:02     17:52         office           present
161       E0001 2026-08-24    08:12     16:02           home           present
162       E0001 2026-08-25    08:57     17:47         office           present
163       E0001 2026-08-26    08:06     16:52         office           present
164       E0001 2026-08-27    09:37     18:14           home           present
165       E0001 2026-08-28    08:43     17:22         office           present
166       E0001 2026-08-31      NaN       NaN         office           missing

In [17]:
def get_attendance_summary(
    employee_id,
    start_date,
    end_date
):
    """
    Calculate attendance statistics for an employee.
    """

    records = get_attendance(
        employee_id,
        start_date,
        end_date
    )

    summary = {
        "employee_id": employee_id,
        "start_date": start_date,
        "end_date": end_date,
        "office_days": int(
            (records["location"] == "office").sum()
        ),
        "home_days": int(
            (records["location"] == "home").sum()
        ),
        "business_trip_days": int(
            (records["location"] == "business_trip").sum()
        ),
        "sick_days": int(
            (records["status"] == "sick").sum()
        ),
        "leave_days": int(
            (records["status"] == "leave").sum()
        ),
        "missing_records": int(
            records["status"].isin(
                ["missing", "missing_checkout"]
            ).sum()
        )
    }

    return summary

In [18]:
summary = get_attendance_summary(
    employee_id="E0001",
    start_date="2026-08-01",
    end_date="2026-08-31"
)

print(summary)

{'employee_id': 'E0001', 'start_date': '2026-08-01', 'end_date': '2026-08-31', 'office_days': 15, 'home_days': 5, 'business_trip_days': 1, 'sick_days': 0, 'leave_days': 0, 'missing_records': 3}

In [19]:
def find_missing_attendance(
    employee_id,
    start_date,
    end_date
):
    """
    Find missing check-ins and check-outs
    for an employee.
    """

    records = get_attendance(
        employee_id,
        start_date,
        end_date
    )

    missing = records[
        records["status"].isin(
            ["missing", "missing_checkout"]
        )
    ].copy()

    return missing

In [20]:
missing = find_missing_attendance(
    employee_id="E0001",
    start_date="2026-08-01",
    end_date="2026-08-31"
)

display(missing)

    employee_id       date check_in check_out location            status
152       E0001 2026-08-11      NaN       NaN     home           missing
155       E0001 2026-08-14    08:46       NaN   office  missing_checkout
166       E0001 2026-08-31      NaN       NaN   office           missing

In [21]:
def calculate_working_hours(
    employee_id,
    start_date,
    end_date
):
    """
    Calculate total recorded working hours
    for an employee within a date range.
    """

    records = get_attendance(
        employee_id,
        start_date,
        end_date
    )

    records = records[
        records["check_in"].notna() &
        records["check_out"].notna()
    ].copy()

    records["check_in_time"] = pd.to_datetime(
        records["check_in"],
        format="%H:%M"
    )

    records["check_out_time"] = pd.to_datetime(
        records["check_out"],
        format="%H:%M"
    )

    records["hours"] = (
        records["check_out_time"] -
        records["check_in_time"]
    ).dt.total_seconds() / 3600

    return round(records["hours"].sum(), 2)

In [22]:
hours = calculate_working_hours(
    employee_id="E0001",
    start_date="2026-08-01",
    end_date="2026-08-31"
)

print(f"Total working hours: {hours}")

Total working hours: 148.65

In [23]:
def get_employee(employee_id):
    """
    Return employee information.
    """

    result = employees[
        employees["employee_id"] == employee_id
    ]

    if result.empty:
        return None

    return result.iloc[0].to_dict()

In [24]:
employee = get_employee("E0001")

print(employee)

{'employee_id': 'E0001', 'name': 'Anna Müller', 'department': 'Data & AI', 'role': 'Data Analyst', 'employment_type': 'Full-time', 'vacation_days': 30, 'weekly_hours': 40, 'office_location': 'Stuttgart', 'manager_id': nan, 'email': 'anna.mueller@nexatech.example'}

In [25]:
def get_leave(
    employee_id,
    start_date=None,
    end_date=None
):
    """
    Return leave records for an employee.
    """

    result = leave[
        leave["employee_id"] == employee_id
    ].copy()

    if start_date is not None:
        start_date = pd.to_datetime(start_date)

        result = result[
            result["start_date"] >= start_date
        ]

    if end_date is not None:
        end_date = pd.to_datetime(end_date)

        result = result[
            result["end_date"] <= end_date
        ]

    return result

In [26]:
employee_leave = get_leave(
    employee_id="E0001"
)

display(employee_leave)

  leave_id employee_id start_date   end_date      type    status  days
0   L00001       E0001 2026-01-08 2026-01-08  vacation  approved     1
1   L00002       E0001 2026-01-21 2026-01-21      sick  approved     1
2   L00003       E0001 2026-02-12 2026-02-12  vacation  approved     1
3   L00004       E0001 2026-02-17 2026-02-17      sick  approved     1
4   L00005       E0001 2026-03-05 2026-03-05  vacation  approved     1
5   L00006       E0001 2026-04-09 2026-04-09  vacation  approved     1
6   L00007       E0001 2026-06-09 2026-06-09  vacation  approved     1
7   L00008       E0001 2026-07-16 2026-07-16  vacation   pending     1

In [27]:
def get_leave_balance(employee_id):
    """
    Calculate remaining approved vacation days.
    """

    employee = get_employee(employee_id)

    if employee is None:
        return None

    vacation_entitlement = employee["vacation_days"]

    approved_leave = leave[
        (leave["employee_id"] == employee_id) &
        (leave["type"] == "vacation") &
        (leave["status"] == "approved")
    ]

    used_vacation = approved_leave["days"].sum()

    remaining = vacation_entitlement - used_vacation

    return {
        "employee_id": employee_id,
        "vacation_entitlement": int(vacation_entitlement),
        "vacation_used": int(used_vacation),
        "vacation_remaining": int(remaining)
    }

In [28]:
balance = get_leave_balance("E0001")

print(balance)

{'employee_id': 'E0001', 'vacation_entitlement': 30, 'vacation_used': 5, 'vacation_remaining': 25}